site_default:
    resource: "@SiteDefaultBundle/Resources/config/routing.yml"
    prefix:   /

site_common:
    resource: "@SiteCommonBundle/Resources/config/routing.yml"
    prefix:   /common

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
